In [14]:
import numpy as np

X = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
])

D = np.array([[0], [0], [1], [1]])

In [15]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

In [16]:
def calc_output(W, x):
    v = np.matmul(W, x)
    y = sigmoid(v)
    
    return y

In [17]:
def calc_error(d, y):
    e = d - y
    delta = y * (1 - y) * e
    
    return delta

In [18]:
import sympy as sym

z = sym.Symbol('z')
s = 1 / (1 + sym.exp(-z))

sym.diff(s)

exp(-z)/(1 + exp(-z))**2

In [19]:
def delta_GD(W, X, D, alpha):
    for k in range(4):
        x = X[k, :].T
        d = D[k]
        
        y = calc_output(W, x)
        delta = calc_error(d, y)
        
        dW = alpha * delta * x
        W = W + dW
        
    return W

In [20]:
alpha = 0.9
for epoch in range(10000):
    W = delta_GD(W, X, D, alpha)
    print(W)

[[-0.71545991  0.77142457  0.32326816]]
[[-0.48577713  0.73772413  0.29564047]]
[[-0.26975646  0.69176469  0.25406614]]
[[-0.06705193  0.63644102  0.19946104]]
[[0.12367812 0.57487868 0.13441544]]
[[0.30392887 0.51009865 0.06230325]]
[[ 0.47490641  0.44486137 -0.0134177 ]]
[[ 0.63739604  0.38149848 -0.08972561]]
[[ 0.79182599  0.32175406 -0.16434666]]
[[ 0.93841355  0.26671738 -0.23583745]]
[[ 1.07730813  0.2168787  -0.30347808]]
[[ 1.20868732  0.17227052 -0.36706896]]
[[ 1.33279945  0.13263039 -0.42672387]]
[[ 1.44996674  0.0975393  -0.48271071]]
[[ 1.56056802  0.06651882 -0.53535067]]
[[ 1.66501515  0.03909012 -0.58496382]]
[[ 1.76373136  0.01480519 -0.63184478]]
[[ 1.85713457 -0.00673957 -0.67625495]]
[[ 1.94562606 -0.02589975 -0.71842262]]
[[ 2.02958367 -0.04298465 -0.75854637]]
[[ 2.10935849 -0.05826137 -0.79679926]]
[[ 2.1852737  -0.07195968 -0.83333284]]
[[ 2.25762502 -0.08427698 -0.86828067]]
[[ 2.32668203 -0.09538286 -0.90176115]]
[[ 2.39268988 -0.10542317 -0.93387994]]
[[ 2.4

[[ 7.29484635 -0.21838213 -3.43075685]]
[[ 7.29578862 -0.21837611 -3.43123422]]
[[ 7.29673005 -0.2183701  -3.43171115]]
[[ 7.29767062 -0.2183641  -3.43218765]]
[[ 7.29861034 -0.21835811 -3.43266371]]
[[ 7.29954921 -0.21835212 -3.43313935]]
[[ 7.30048723 -0.21834614 -3.43361455]]
[[ 7.30142441 -0.21834017 -3.43408932]]
[[ 7.30236074 -0.2183342  -3.43456365]]
[[ 7.30329623 -0.21832824 -3.43503756]]
[[ 7.30423088 -0.21832229 -3.43551104]]
[[ 7.30516469 -0.21831634 -3.4359841 ]]
[[ 7.30609766 -0.21831041 -3.43645672]]
[[ 7.30702979 -0.21830447 -3.43692892]]
[[ 7.30796109 -0.21829855 -3.4374007 ]]
[[ 7.30889155 -0.21829263 -3.43787204]]
[[ 7.30982119 -0.21828672 -3.43834297]]
[[ 7.31074999 -0.21828081 -3.43881347]]
[[ 7.31167796 -0.21827491 -3.43928355]]
[[ 7.3126051  -0.21826902 -3.4397532 ]]
[[ 7.31353141 -0.21826314 -3.44022244]]
[[ 7.3144569  -0.21825726 -3.44069125]]
[[ 7.31538157 -0.21825139 -3.44115965]]
[[ 7.31630542 -0.21824552 -3.44162762]]
[[ 7.31722844 -0.21823967 -3.44209518]]


[[ 8.14249503 -0.21361345 -3.85924814]]
[[ 8.14290958 -0.21361144 -3.85945729]]
[[ 8.14332397 -0.21360943 -3.85966636]]
[[ 8.14373819 -0.21360742 -3.85987533]]
[[ 8.14415225 -0.21360541 -3.86008423]]
[[ 8.14456614 -0.2136034  -3.86029304]]
[[ 8.14497986 -0.2136014  -3.86050176]]
[[ 8.14539341 -0.21359939 -3.8607104 ]]
[[ 8.1458068  -0.21359739 -3.86091895]]
[[ 8.14622002 -0.21359538 -3.86112743]]
[[ 8.14663307 -0.21359338 -3.86133581]]
[[ 8.14704596 -0.21359138 -3.86154411]]
[[ 8.14745868 -0.21358938 -3.86175233]]
[[ 8.14787124 -0.21358738 -3.86196047]]
[[ 8.14828363 -0.21358538 -3.86216852]]
[[ 8.14869585 -0.21358339 -3.86237648]]
[[ 8.14910791 -0.21358139 -3.86258436]]
[[ 8.1495198  -0.2135794  -3.86279216]]
[[ 8.14993153 -0.2135774  -3.86299988]]
[[ 8.15034309 -0.21357541 -3.86320751]]
[[ 8.15075449 -0.21357342 -3.86341506]]
[[ 8.15116572 -0.21357143 -3.86362252]]
[[ 8.15157679 -0.21356944 -3.8638299 ]]
[[ 8.15198769 -0.21356745 -3.8640372 ]]
[[ 8.15239843 -0.21356547 -3.86424441]]


[[ 8.54719229 -0.21179292 -4.06325964]]
[[ 8.54747146 -0.21179176 -4.06340026]]
[[ 8.54775055 -0.2117906  -4.06354085]]
[[ 8.54802956 -0.21178945 -4.0636814 ]]
[[ 8.5483085  -0.21178829 -4.0638219 ]]
[[ 8.54858736 -0.21178713 -4.06396238]]
[[ 8.54886615 -0.21178597 -4.06410281]]
[[ 8.54914485 -0.21178482 -4.0642432 ]]
[[ 8.54942349 -0.21178366 -4.06438355]]
[[ 8.54970205 -0.21178251 -4.06452387]]
[[ 8.54998053 -0.21178135 -4.06466415]]
[[ 8.55025893 -0.2117802  -4.06480439]]
[[ 8.55053726 -0.21177904 -4.06494459]]
[[ 8.55081552 -0.21177789 -4.06508475]]
[[ 8.55109369 -0.21177674 -4.06522488]]
[[ 8.5513718  -0.21177558 -4.06536496]]
[[ 8.55164982 -0.21177443 -4.06550501]]
[[ 8.55192777 -0.21177328 -4.06564502]]
[[ 8.55220565 -0.21177213 -4.06578499]]
[[ 8.55248345 -0.21177098 -4.06592493]]
[[ 8.55276117 -0.21176983 -4.06606482]]
[[ 8.55303882 -0.21176868 -4.06620468]]
[[ 8.55331639 -0.21176753 -4.0663445 ]]
[[ 8.55359389 -0.21176638 -4.06648428]]
[[ 8.55387131 -0.21176523 -4.06662402]]


[[ 8.87039519 -0.21053562 -4.22597845]]
[[ 8.87059852 -0.21053488 -4.22608076]]
[[ 8.8708018  -0.21053414 -4.22618305]]
[[ 8.87100505 -0.2105334  -4.22628533]]
[[ 8.87120825 -0.21053266 -4.22638758]]
[[ 8.87141142 -0.21053192 -4.22648981]]
[[ 8.87161454 -0.21053119 -4.22659202]]
[[ 8.87181763 -0.21053045 -4.22669421]]
[[ 8.87202067 -0.21052971 -4.22679638]]
[[ 8.87222367 -0.21052897 -4.22689853]]
[[ 8.87242663 -0.21052824 -4.22700066]]
[[ 8.87262955 -0.2105275  -4.22710277]]
[[ 8.87283244 -0.21052676 -4.22720486]]
[[ 8.87303528 -0.21052602 -4.22730692]]
[[ 8.87323808 -0.21052529 -4.22740897]]
[[ 8.87344084 -0.21052455 -4.227511  ]]
[[ 8.87364356 -0.21052382 -4.22761301]]
[[ 8.87384623 -0.21052308 -4.22771499]]
[[ 8.87404887 -0.21052234 -4.22781696]]
[[ 8.87425147 -0.21052161 -4.2279189 ]]
[[ 8.87445403 -0.21052087 -4.22802083]]
[[ 8.87465655 -0.21052014 -4.22812274]]
[[ 8.87485902 -0.2105194  -4.22822462]]
[[ 8.87506146 -0.21051867 -4.22832648]]
[[ 8.87526386 -0.21051793 -4.22842833]]


[[ 9.07291851 -0.20982993 -4.32785708]]
[[ 9.07308512 -0.20982938 -4.32794087]]
[[ 9.07325172 -0.20982882 -4.32802465]]
[[ 9.07341828 -0.20982827 -4.32810841]]
[[ 9.07358482 -0.20982771 -4.32819216]]
[[ 9.07375133 -0.20982715 -4.3282759 ]]
[[ 9.07391781 -0.2098266  -4.32835963]]
[[ 9.07408426 -0.20982604 -4.32844334]]
[[ 9.07425069 -0.20982549 -4.32852703]]
[[ 9.07441709 -0.20982493 -4.32861071]]
[[ 9.07458346 -0.20982438 -4.32869438]]
[[ 9.07474981 -0.20982383 -4.32877804]]
[[ 9.07491613 -0.20982327 -4.32886168]]
[[ 9.07508242 -0.20982272 -4.32894531]]
[[ 9.07524868 -0.20982216 -4.32902892]]
[[ 9.07541492 -0.20982161 -4.32911252]]
[[ 9.07558113 -0.20982105 -4.32919611]]
[[ 9.07574731 -0.2098205  -4.32927968]]
[[ 9.07591347 -0.20981995 -4.32936324]]
[[ 9.0760796  -0.20981939 -4.32944678]]
[[ 9.0762457  -0.20981884 -4.32953032]]
[[ 9.07641177 -0.20981829 -4.32961383]]
[[ 9.07657782 -0.20981773 -4.32969734]]
[[ 9.07674384 -0.20981718 -4.32978083]]
[[ 9.07690983 -0.20981663 -4.3298643 ]]


[[ 9.26169418 -0.20922516 -4.42276817]]
[[ 9.26183253 -0.20922473 -4.42283771]]
[[ 9.26197087 -0.20922431 -4.42290725]]
[[ 9.26210918 -0.20922388 -4.42297677]]
[[ 9.26224748 -0.20922346 -4.42304629]]
[[ 9.26238576 -0.20922303 -4.42311579]]
[[ 9.26252402 -0.20922261 -4.42318529]]
[[ 9.26266227 -0.20922218 -4.42325478]]
[[ 9.26280049 -0.20922176 -4.42332425]]
[[ 9.26293869 -0.20922133 -4.42339372]]
[[ 9.26307688 -0.20922091 -4.42346318]]
[[ 9.26321505 -0.20922048 -4.42353263]]
[[ 9.26335319 -0.20922006 -4.42360207]]
[[ 9.26349132 -0.20921963 -4.4236715 ]]
[[ 9.26362943 -0.20921921 -4.42374092]]
[[ 9.26376753 -0.20921879 -4.42381033]]
[[ 9.2639056  -0.20921836 -4.42387973]]
[[ 9.26404365 -0.20921794 -4.42394912]]
[[ 9.26418169 -0.20921751 -4.42401851]]
[[ 9.2643197  -0.20921709 -4.42408788]]
[[ 9.2644577  -0.20921667 -4.42415724]]
[[ 9.26459568 -0.20921624 -4.4242266 ]]
[[ 9.26473364 -0.20921582 -4.42429594]]
[[ 9.26487158 -0.2092154  -4.42436528]]
[[ 9.26500951 -0.20921497 -4.4244346 ]]


[[ 9.42540355 -0.20873961 -4.50503942]]
[[ 9.42552128 -0.20873928 -4.50509858]]
[[ 9.425639   -0.20873894 -4.50515772]]
[[ 9.42575671 -0.2087386  -4.50521686]]
[[ 9.4258744  -0.20873827 -4.505276  ]]
[[ 9.42599207 -0.20873793 -4.50533512]]
[[ 9.42610974 -0.2087376  -4.50539424]]
[[ 9.42622739 -0.20873726 -4.50545336]]
[[ 9.42634503 -0.20873692 -4.50551246]]
[[ 9.42646265 -0.20873659 -4.50557156]]
[[ 9.42658026 -0.20873625 -4.50563065]]
[[ 9.42669785 -0.20873591 -4.50568974]]
[[ 9.42681544 -0.20873558 -4.50574882]]
[[ 9.42693301 -0.20873524 -4.50580789]]
[[ 9.42705056 -0.20873491 -4.50586695]]
[[ 9.4271681  -0.20873457 -4.50592601]]
[[ 9.42728563 -0.20873423 -4.50598506]]
[[ 9.42740314 -0.2087339  -4.50604411]]
[[ 9.42752064 -0.20873356 -4.50610314]]
[[ 9.42763813 -0.20873323 -4.50616217]]
[[ 9.4277556  -0.20873289 -4.5062212 ]]
[[ 9.42787306 -0.20873256 -4.50628021]]
[[ 9.42799051 -0.20873222 -4.50633922]]
[[ 9.42810794 -0.20873189 -4.50639823]]
[[ 9.42822536 -0.20873155 -4.50645722]]


[[ 9.55798016 -0.20837144 -4.57164157]]
[[ 9.55808346 -0.20837116 -4.57169346]]
[[ 9.55818674 -0.20837088 -4.57174534]]
[[ 9.55829001 -0.2083706  -4.57179721]]
[[ 9.55839327 -0.20837033 -4.57184908]]
[[ 9.55849652 -0.20837005 -4.57190094]]
[[ 9.55859976 -0.20836977 -4.57195279]]
[[ 9.55870299 -0.20836949 -4.57200465]]
[[ 9.55880621 -0.20836921 -4.57205649]]
[[ 9.55890942 -0.20836893 -4.57210833]]
[[ 9.55901262 -0.20836866 -4.57216017]]
[[ 9.55911581 -0.20836838 -4.572212  ]]
[[ 9.55921898 -0.2083681  -4.57226382]]
[[ 9.55932215 -0.20836782 -4.57231564]]
[[ 9.55942531 -0.20836754 -4.57236746]]
[[ 9.55952845 -0.20836727 -4.57241927]]
[[ 9.55963159 -0.20836699 -4.57247107]]
[[ 9.55973471 -0.20836671 -4.57252287]]
[[ 9.55983783 -0.20836643 -4.57257466]]
[[ 9.55994093 -0.20836616 -4.57262645]]
[[ 9.56004402 -0.20836588 -4.57267823]]
[[ 9.5601471  -0.2083656  -4.57273001]]
[[ 9.56025018 -0.20836532 -4.57278178]]
[[ 9.56035324 -0.20836505 -4.57283355]]
[[ 9.56045629 -0.20836477 -4.57288531]]


In [22]:
N = 4

for k in range(N):
    x = X[k, :].T
    v = np.matmul(W, x)
    y = sigmoid(v)
    
    print(y)

[0.01020061]
[0.008298]
[0.99323846]
[0.99168519]
